### ISSUE TITLE
Extends an exists packages?

### ISSUE THREAD

**Issue by jwu** [cocos-creator/editor-framework#18]
This is just a discussion for an idea that I'm thinking about. I want to share it and listen to the advice. Use Chinese if you wish. @YuJianrong @nantas @jareguo @yorkie 

Basically I wish I can extends an exists packages without introduce new panels, assets or other things. To make this possible, the best way is I can just mixins or extends the original code without changing the panel ID, asset's name or other things link to package registry. 

Why this? Why not use a barely new panel, new asset or new meta ...? 

Here I only talk about panel, but asset, meta may have similar ideas, I'm not sure, and we will back to discuss them once I'm working on it.

**mixin exists panels**

We have to face a truth that most of our `Editor.Panel` operation working depends on panelID. Some IPC messages will go directly to the panel (`Editor.sendToPanel(panelID,...)`) and give no chance for other people listening on it. Even if we carefully design the interface for extension,  some panel packages still can grow up that makes it non-replaceable for users, especially panels like `fire-assets`, `fire-inspector` and `fire-console`. 

Take `fire-assets` for example, I want it listen to 'foo:bar' and do something (change the background of assets the message gives). It is easy if we provide the keyword `mixins` in our package.json.

```json
"panels": {
  "fire-assets.panel": {
    "mixins": [ "your/mixin/script1.js", "your/mixin/script2.js" ],
    "messages": [
      "my:ipc-message-1",
      "my:ipc-message-2"
    ],
    "shortcuts": {
      "command+k": "my-method"
    },
  }
}
```

What mixins gonna do is very simple, it just `require` your script, load all properties in it, and apply them to the panel define through panel ID you provided ('fire-assetss.panel' above). If your script have the same property with the original panel define, a warning will raise. In this way, it make sure mixins will not broke the original package.

So mixin packages here won't give you any thing new, you don't get a new panel once you install this package. It only enhance the exists panel you have, so people can pickup the extensions they like and need not to replace the whole panel they used to work.

**Use main.js load and unload method to register new stuff**

`main.js` is a good way to process user's own register method, and it prevent us introduce too many keyword in `package.json`. For instance, in `fire-inspector`, I've designed so many things so that he have the ability to inspect different structures ( importer-inspector, entity-inspector, custom-asset-inspector, ...). If people want another structure for inspecting it, in the old way, he should read the manual of fireball and follow the instruct to register a new inspector in `package.json` file, just like this:

```json
"inspector": {
  "my-type": "widget/my-inspector.html"
}
```

So every time `my-type` been selected, the `fire-inspector` will use `widget/my-inspector.html` present the data. Of course this need we add `inspector` as a new field in Fireball (An Editor-Framework App), and add our method so that we can parse things in this field and register the new inspector internally. Thanks god `fire-inspector` is developed by Fireball Team, so they can reform the parser behind the `package.json` to what they like. 

What if I'm a 3rd party developer, what if I wish my packages can do what `fire-inspector` does. Should I add new keyword in `package.json`? Of corse I can't, and `fire-inspector` is a bad practice here. Basically I believe all packages should be treated as first-class citizens, so I believe no packages deserve a seat in `package.json` and force the Editor Framework App (here is Fireball) served him. Remember, with great power, comes great responsibility. WTF are you spider man? (joke)

Instead, I think the `main.js` is good for this job. Every packages can load a script that define in `main` keyword, which is in common. And the main script will execute the `load`, `unload` method in it. Even awesome, we can freely register ipc message directly in the main script. For `fire-inspector`, its main.js looks like this:

```javascript
// fire-inspector's main.js
module.exports = {
  'fire-inspector:register': function ( type, path ) {
    // do something
  },
  'fire-inspector:unregister': function ( type, path ) {
    // do something
  },
}
```

And for packages who just want to register inspector for its own type, its main.js looks like this:

```javascript
// my inspector extensions' main.js
module.exports = {
  load: function () {
    Editor.sendToPackage( 'fire-inspector', 'fire-inspector:register', 'my-type', 'widget/my-inspector.html');
  },
  unload: function () {
    Editor.sendToPackage( 'fire-inspector', 'fire-inspector:unregister', 'my-type');
  },
}
```

**Comment by VinciShark** [comment]
同上，能fork就行
