### ISSUE TITLE
New Window instead of new panel

### ISSUE THREAD

**Issue by WolfieWerewolf** [cocos-creator/editor-framework#248]
Hi Guys... I just cloned as per the instructions, installed as described and the demo will launch but instead of new panels being docked it's creating new windows?  Am I doing something wrong?

Thanks

/W

**Comment by jwu** [comment]
Hi Wolfile,

Can you give me more details about your question? What do you mean "creating new windows?"

**Comment by WolfieWerewolf** [comment]
Hi,

Thanks for the quick response.  By "Creating New Windows" I mean that a 
new instance of Browser Window / Render Process is created instead of a 
panel in the main Render process.

Does that make more sense?

/W

**Comment by jwu** [comment]
Hi Wolfie,

If you start a Editor Framework, it will first check if here is a layout in .settings folder, if not it will use default layout for the first Window (main window). After that, when you use Editor.Panel.open to open a panel, it will first open in new window, and you can manually drag it to your main window.

To custom your default layout, try this example: https://github.com/exsdk/example-apps/tree/master/custom-layout
