### ISSUE TITLE
Is it work fine with react.js+flux?

### ISSUE THREAD

**Issue by VinciShark** [cocos-creator/editor-framework#258]
Is it work fine with react.js+flux?
是否可以和react.js+flux一起工作？
想在panel里使用react.js写控件，不知道会不会有兼容性问题

**Comment by jwu** [comment]
It works. 

I've remove the dependencies of Polymer in the latest version. The whole framework is writing in pure HTML5. In this way, it allow people integrate different GUI framework with it.

I'm really happy to see some one use React with it. Any problem, let me known.

**Comment by VinciShark** [comment]
Thanks for the wonderful framework you guys creat.
I am ready to use this framework in a very cool project.
Keep touch @jwu

**Comment by jwu** [comment]
Cool man. Keep in touch.

May I have your QQ number? (You can send it through E-Mail: KarasAya@gmail.com)

**Comment by VinciShark** [comment]
root@vinci.pro QQ号也可以搜这个
