### ISSUE TITLE
node --version v6.2.0 getting error : (node:3052) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module

### ISSUE THREAD

**Issue by meiry** [cocos-creator/editor-framework#283]
when trying to install using this command : 
npm install --save editor-framework
im getting this error : 
```
D:\dev\electron\editor-framework>npm install --save editor-framework
(node:3052) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\dev\\nodejs\\node.exe" "C:\\Users\\meirmaya\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "editor-framework"
npm ERR! node v6.2.0
npm ERR! npm  v3.3.8
npm ERR! code ENOSELF

npm ERR! Refusing to install editor-framework as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\dev\electron\editor-framework\npm-debug.log

D:\dev\electron\editor-framework>npm -g list graceful-fs
C:\Users\meirmaya\AppData\Roaming\npm
├─┬ electron-prebuilt@1.1.1
│ └─┬ electron-download@2.1.2
│   └─┬ nugget@1.6.2
│     └─┬ pretty-bytes@1.0.4
│       └─┬ meow@3.7.0
│         └─┬ read-pkg-up@1.0.1
│           └─┬ read-pkg@1.1.0
│             └─┬ load-json-file@1.1.0
│               └── graceful-fs@4.1.4
├─┬ gulp@3.9.1
│ ├─┬ gulp-util@3.0.7
│ │ └─┬ dateformat@1.0.12
│ │   └─┬ meow@3.7.0
│ │     └─┬ read-pkg-up@1.0.1
│ │       └─┬ read-pkg@1.1.0
│ │         └─┬ load-json-file@1.1.0
│ │           └── graceful-fs@4.1.3
│ └─┬ vinyl-fs@0.3.14
│   ├─┬ glob-watcher@0.0.6
│   │ └─┬ gaze@0.5.2
│   │   └─┬ globule@0.1.0
│   │     └─┬ glob@3.1.21
│   │       └── graceful-fs@1.2.3
│   └── graceful-fs@3.0.8
├─┬ jitsu@0.15.0
│ ├─┬ fstream@0.1.25
│ │ └── graceful-fs@2.0.3
│ └─┬ require-analyzer@0.5.0
│   └─┬ read-installed@0.0.4
│     ├── graceful-fs@1.1.14
│     └─┬ read-package-json@0.4.1
│       └── graceful-fs@1.2.3
└─┬ npm@3.3.8
  ├─┬ cmd-shim@2.0.1
  │ └── graceful-fs@3.0.8
  └── graceful-fs@4.1.2


D:\dev\electron\editor-framework>node --version
v6.2.0
```

**Comment by yorkie** [comment]
This seems to be a breaking change from community, you need to clean your node_modules and try to install again.

**Comment by meiry** [comment]
i delete all node_modules dir now it dos not start ,,, ( im not node .js developer )

**Comment by jwu** [comment]
hi @meiry 

Your first question has been confirmed by @yorkie, I can double confirm it works in node v6.2.0 just now.

Your second problem is: you are trying to install editor-framework in a project named editor-framework. That is invalid for node. Please try:

 1. create your node project, such as my-app
 2. `npm init`
 3. `npm install --save editor-framework` in it

**Comment by meiry** [comment]
Thanks for replying but i still have problems , now im on different computer and i have different errors 
can it be as 1 containing it all package to download ?
attaching error log
[npm-debug.txt](https://github.com/cocos-creator/editor-framework/files/294906/npm-debug.txt)

**Comment by jwu** [comment]
hi @meiry 

You npm-debug.txt shows you are running on network problem.

What do you mean as 1 containing it all package? editor-framework is just an Electron module to help people developing IDE like apps in Electron, so everything follow the way node or Electron did.

**Comment by meiry** [comment]
i can download every thing here , so no network problem Unless this firewall here blocks the links you are referring to ... ( cocos studio problem where the anti virus was blocking stuff ) .
what i mean in 1 contains all package , is to be able to install it without going via downloading stuff from the network .

**Comment by jwu** [comment]
@meiry 

> what i mean in 1 contains all package , is to be able to install it without going via downloading stuff from the network .

This is not editor-framework mean to be. As I mentioned in last comment, the editor-framework is just an electron module, so it follows the way what Electron's community did. If you find this is difficult for you to get started, you probably needs to learn some basic knowledge staring from [Electron](electron.atom.io) and [node](nodejs.org).
