### ISSUE TITLE
Error: ReferenceError: Polymer is not defined

### ISSUE THREAD

**Issue by yblunan** [cocos-creator/editor-framework#311]
When I use ui-kit package and uk-tree 

I try " npm install Polymer"     Polymer@1.4.0 node_modules/Polymer

**Comment by jwu** [comment]
The ui-kit and ui-tree package is deprecated, I've add internal ui-kit and you can use ui-kit-preview package to preview and learn it.

The ui-tree will be replaced by a new one. 

If you insist of using these packages, you need to use `bower install Polymer` so it will go to bower_components/ to make ui-kit and ui-tree reference it properly.

**Comment by yblunan** [comment]
thanks.
waiting for your tree view
