### ISSUE TITLE
Updating code in packages or layout.json has often has no effect, even after full restart

### ISSUE THREAD

**Issue by Aerlinger** [cocos-creator/editor-framework#316]
I've been having a lot of difficulty getting my package/layout code to be consistent with what I expect to see in Electron. It seems like the results of my code are always out of sync most likely due to caching or an obsolete file reference.

For example, if I download the "example-apps" code to a fresh directory, link it to `editor-framework`, all examples will build and run fine the first time:
![image](https://cloud.githubusercontent.com/assets/604138/16543352/23ddcc3e-409e-11e6-9dab-6a7f0cfaf75d.png)

However, changing any of the package or layout.json code, usually has no effect. I can even sometimes delete required files like layout.json and it will still run with no change.

This has occurred both in the example code and in my own code, though the results are often unpredictable and inconsistent. I assume it has something to with module reloading, however starting the main process with a different file/port doesn't always fix the issue (though it does sometimes).

The only common symptom is that it seems to be specific to code within packages and perhaps also some persistent configuration settings like window position size.

Any thoughts on this? Has anyone experienced something similar?

**Comment by VinciShark** [comment]
What kind of app are you using editor-framework for?

**Comment by jwu** [comment]
Hi @Aerlinger ,

The layout.json only calculate your layout at the first time (when there is no layout found in `${App.home}/local/layout.windows.json`). If the `layout.windows.json` was found, it will load layout from it. This file is created when you dock a window or quit the app. It will restore your layout to the last time you see.

**Comment by Aerlinger** [comment]
@VinciShark Just exploring for the time being.

@jwu That makes sense given what I've seen, but how would I change or specify the layout of the app programatically?

**Comment by jwu** [comment]
@Aerlinger , currently there is no easy way to do this. There is a interface relative with it:

```javascript
Editor.UI.DockUtils.resetLayout
```

You can check what the parameters send to it through these code: https://github.com/cocos-creator/editor-framework/blob/master/lib/renderer/ui/utils/dock-utils.js#L292

Sorry there is not too much document on this, since I'm going to have a re-design on the dock system. I think I will provide a better way to allow user define their default layout, and give a `fixed-layout` option for user.

**Comment by Aerlinger** [comment]
Thanks, is there a usage example for `Editor.UI.DockUtils.resetLayout` anywhere?

I'm trying the following:

```javascript
init(opts, cb) {
    let settingsPath = Path.join(Editor.App.path, '.settings');

    editor = Editor.init({
      'profile':             {
        local: settingsPath,
      },
      'package-search-path': [
        Editor.url('app://packages/'),
        Editor.url('app://package-examples/'),
      ],
      'panel-window':        'app://window.html',
      'layout':              Editor.url('app://layout.json'),
    });

    Editor.UI.DockUtils.resetLayout(editor, editor.layout, cb)

    if (cb) {
      cb();
    }
  },
```

But getting:

```
[58745]Uncaught Exception:  Error: TypeError: app.terminate is not a function
ReferenceError: editor is not defined
    at Async.series.err (editor-framework/index.js:330:13)
```

**Comment by jwu** [comment]
so far, I only use it in here: https://github.com/cocos-creator/editor-framework/blob/master/lib/renderer/ui/dock/main-dock.js

**Comment by Aerlinger** [comment]
Trying to implement this but still running into the same error I've shown above. Regarding this point:

> The layout.json only calculate your layout at the first time (when there is no layout found in ${App.home}/local/layout.windows.json). If the layout.windows.json was found, it will load layout from it. This file is created when you dock a window or quit the app. It will restore your layout to the last time you see.

This seems as though it would make sense in production, but what about a workflow for previewing changes in development? In other words, it seems as though there should a simple way for the developer to preview layout related changes to the app without loading settings `${App.home}/local/layout.windows.json`.

**Comment by jwu** [comment]
Hi @Aerlinger , Have you try Reset Layout menu? 

![screen shot 2016-07-18 at 11 04 08 am](https://cloud.githubusercontent.com/assets/174891/16905353/568c03a4-4cd7-11e6-91b7-68fdb79b8e0d.png)

It will reset the layout to your default settings. You can also refer the code to extends it: https://github.com/cocos-creator/editor-framework/blob/master/lib/main/main-menu.js#L296

I agree we need to improve the workflow, but currently have no idea how to do it. Any suggestion?

**Comment by Aerlinger** [comment]
I think a reasonable approach here is to detect a change in an app's or package's `layout.json` by comparing it to what's cached in the `.settings` path . If `layout.json` has changed, then perhaps the `.settings` should be updated to reflect the latest. 

At the very least this should be default behavior for development.

**Comment by jwu** [comment]
Not a bad idea. 👍
