### ISSUE TITLE
Correct capitalization/hyphenation for editor-framework?

### ISSUE THREAD

**Issue by Aerlinger** [cocos-creator/editor-framework#339]
I've seen the following variations across the code, comments, and docs:

- `editor-framework`
- `Editor-Framework`
- `editor framework`
- `Editor Framework`

Which is correct? Would be good to formalize for consistency's sake.

**Comment by VinciShark** [comment]
Editor-Framework looks better?

**Comment by Aerlinger** [comment]
@VinciShark Agreed.

**Comment by jwu** [comment]
Editor-Framework is fine to me.

BTW: There's only one place use editor-framework --- the `editor-framework://` protocol.
