### ISSUE TITLE
Adding an invalid package search path in `Editor.init(...)` doesn't raise error or warning

### ISSUE THREAD

**Issue by Aerlinger** [cocos-creator/editor-framework#341]
Here's an example:

Main entry script:
```javascript
//...
init(opts, callback) {
   Editor.init({
      'package-search-path': [
        Editor.url('app://some-nonsense-path/')
      ]
    });
   callback()
}
...
```

The app runs fine, no warnings or errors are raised despite the fact that `app://some-nonsense-path/` doesn't exist as package path.

**Comment by jwu** [comment]
The search-path configuration in most system is silent. Such as: Vim, OS Environment Path, programme language's module system, Visual Studio Linking System.

I just inherit the behivor :)

**Comment by Aerlinger** [comment]
Hm... I agree with silent behavior in those exampls. For VIM and my OS my PATH often contains locations that don't exist at startup because some programs might dynamically create or delete folders during the lifecycle of the app. 

However, I'm trying to think of a case in Editor-Framework where a user would have an invalid path that was deliberate. In fact, in Editor-Framework It seems like an invalid path would be much more likely to be a result of user error. In any event, I don't think an error would be appropriate, but perhaps a warning or an info log to notify the user of the invalid path would be.

**Comment by jwu** [comment]
In the previous version, adding missing search path did raise a warning for user. But we found that sometimes this is reasonable. 

One of my app designed to allow user put there packages in `~/.${app-name}/packages`, so the App's init code writing like this:

```javascript
Editor.init({
  'package-search-path': [
    Editor.url('app://pacakges'), 
    Path.join( Editor.App.home, 'packages')
  ]
});
```

For user who running this App, the App doesn't care about if the `~/.${app-name}/packages` exists, user who wish to add packages will create the folder in their own. 

So if I warn the user by default, the App developer has no chance to silent it. Instead, I think leave it to developer would be better.
