### ISSUE TITLE
Creating custom UI elements

### ISSUE THREAD

**Issue by Pazza** [cocos-creator/editor-framework#344]
I am trying to define some custom ui elements but within the packages lifecycle, Editor.UI doesn't seem to be loaded yet and I have no way of calling Editor.UI.registerElement.

**Comment by VinciShark** [comment]
Already have the feature. But the Doc is still in progress.

**Comment by jwu** [comment]
Hi @Pazza , here is an example:

Suppose you have a panel define like this, use the `dependencies` keyword to pre-load your ui elements

```javascript
// panel/index.js

'use strict';

Editor.Panel.extend({
  dependencies: [
    'packages://your-pkg-name/foo-bar.js'
  ],

  template: `
    <ui-foo-bar></ui-foo-bar>
  `,

});

```

In your foo-bar.js, just write:

```javascript
Editor.UI.registerElement('ui-foo-bar', {
  template: `Foobar: <input></input>`
});
```

**Comment by Pazza** [comment]
Thank you @jwu. Will give it a try in the morning. Appreciate the time you put into this project.
