### ISSUE TITLE
complex demo available?

### ISSUE THREAD

**Issue by vrmerlin** [cocos-creator/editor-framework#359]
I really like what I see here, but am struggling to get my head wrapped around the documentation. Is there a demo available that I'm not seeing that demonstrates a full multi-pane configuration and some sample panels? The screenshot on the README looks great, but I don't see any actual examples.

Thanks,
John

**Comment by VinciShark** [comment]
Read the repo's README there is a lot of great examples.
https://github.com/cocos-creator/editor-framework#example-apps

**Comment by jwu** [comment]
hi @vrmerlin ,

@VinciShark already answer your question. Is this what you need?

**Comment by vrmerlin** [comment]
Yes,  I found them,  thanks!
