### ISSUE TITLE
Generating documentation

### ISSUE THREAD

**Issue by Aerlinger** [cocos-creator/editor-framework#361]
I think this section of the documentation may be very out of date:

https://github.com/cocos-creator/editor-framework#generate-documentation

There's currently no command to generate API documentation. Can one be added and the docs be updated accordingly?

**Comment by jwu** [comment]
Oh, thanks for remind me to delete this. It is indeed out of date. And instead of auto-gen the API doc, I will write it manually just like what Electron did.
