### ISSUE TITLE
Is there a way to create trees?

### ISSUE THREAD

**Issue by DeathParticle** [cocos-creator/editor-framework#384]
I would like to create some tree controls for my project, for example, file tree or tree of my objects hierarchy
How can I achive this?

I mean something like this: 

![image](https://cloud.githubusercontent.com/assets/20597871/17271122/5617d6ba-567c-11e6-91fd-c135750e32f2.png)

**Comment by jwu** [comment]
Hi @DeathParticle ,

You can take a look at https://github.com/fireball-packages/ui-tree. It is an old way we used in Cocos Creator to process tree view.

Further more, you can also read this issue: https://github.com/fireball-packages/ui-tree/issues/2, in this issue I suggest people to learn Vue and use the example it provides to solve the tree view problem.
