### ISSUE TITLE
Obsolete content in "creating a package" example?

### ISSUE THREAD

**Issue by Aerlinger** [cocos-creator/editor-framework#403]
I'm looking at:

```
MyPackage
  |--(optional)panel
  |   |--panel.js
  |   |--(optional)template.html
  |   |--(optional)style.css
  |--main.js
  |--package.json
```

In https://github.com/cocos-creator/editor-framework/blob/master/docs/packages/create-your-package.md.

How are `(optional)template.html` and `(optional)style.css` supposed to be loaded? There are no specific docs on this anywhere.

**Comment by jwu** [comment]
Oh, should be remove from document.
