### ISSUE TITLE
Tab key event not firing

### ISSUE THREAD

**Issue by KD0NKS** [cocos-creator/editor-framework#438]
The tab key event is not firing when using editor-framework (0.6.4), however it does fire using the same html with a normal electron configuration in the main.js file.  Tested under Windows 10 and Linux (Latest versions of Ubuntu, virtualized and on Raspberry Pi 2) with the same results.

```html
<!doctype html>
<html>
    <head>
        <meta charset='utf-8'>
        <title>Main Window</title>
    </head>
    <body class="layout vertical">
    </body>

    <script type="text/javascript">
        document.addEventListener("keydown", ((e) => {
            console.log(e);
        }), false);
    </script>
</html>
```

**Does not work:**
```javascript
const Editor = require('editor-framework');

Editor.App.extend({
  init(opts, cb) {
    if(cb) cb();
  }
  , run() {
    let mainWin = new Editor.Window('main');
    Editor.Window.main = mainWin;

    mainWin.restorePositionAndSize();

    mainWin.load( 'app://index.html' );
    mainWin.show();
    
    mainWin.focus();
  },
});
```

**Works**
```javascript
const { app , BrowserWindow } = require('electron')

let win;

function createWindow () {
  win = new BrowserWindow({width: 800, height: 600})
  win.loadURL(`file://${__dirname}/index.html`)

  win.on('closed', () => { win = null; })
}

app.on('ready', createWindow)

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
})

app.on('activate', () => {
  if (win === null) createWindow();
})
```

**Comment by jwu** [comment]
The TAB key has been capture and preventByDefault in Editor Framework since we use it to handle focus behaviour by our own.

Would you like to tell me what is your case in using TAB? may be we can find a solution for both.

**Comment by KD0NKS** [comment]
I suspected that could be the case.  In this case, I was working on building a (relatively) light text/code editor on a RPi.  Use of panels being my main reason for using editor-framework.

**Comment by jwu** [comment]
I see. For a temp solution. You can do:

```
Editor.UI._FocusMgr.disabled = true;
```

At the beginning. This will disable the focus-mgr at all and give you back the TAB key.

============

A better solution would be:

When you enter the text editor you running the code above. And when you come out the text editor, turn on the FocusMgr again:

```
Editor.UI._FocusMgr.disabled = false;
```

In this way, all the builtin ui elements will be work fine and you still have your text editor working.

**Comment by KD0NKS** [comment]
Thanks!  Might consider adding that to documentation.

**Comment by jwu** [comment]
I will. I AM thinking to find a better way.
